# Generated by Django 4.0.4 on 2022-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
